#!/bin/sh
### BEGIN INIT INFO
# Provides:          KNXd
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: This file is for the KNXd Plugin.
# Description:       This file is for the KNXd Plugin.
### END INIT INFO

PATH="/sbin:/bin:/usr/sbin:/usr/bin:REPLACEBYBASEFOLDER/bin"
PATH=$PATH.":REPLACEBYBASEFOLDER/sbin"

. /lib/lsb/init-functions

### END INIT INFO

# Version 1.4
# 31.10.2016 23:01:51

logfile=REPLACEBYBASEFOLDER/log/plugins/REPLACEBYSUBFOLDER/knxd.log
flagfile=REPLACEBYBASEFOLDER/config/plugins/REPLACEBYSUBFOLDER/modify.me
configfile=REPLACEBYBASEFOLDER/config/plugins/REPLACEBYSUBFOLDER/knxd.cfg
INPUTFILE="/etc/knxd.conf"
if [ -r $flagfile ]
then
  touch $logfile
  chown loxberry:loxberry $logfile
  chmod 666 $logfile
  echo "modify.me found. Installing KNXd Plugin."
  echo "modify.me found. Installing."                                                                                                                 2>&1 >>$logfile
  cd REPLACEBYBASEFOLDER/data/plugins/REPLACEBYSUBFOLDER/                                                                                             2>&1 >>$logfile
  dpkg -i libpthsem*.deb                                                                                                                              2>&1 >>$logfile
  dpkg -i knxd_*.deb knxd-tools_*.deb                                                                                                                 2>&1 >>$logfile
  cd                                                                                                                                                  2>&1 >>$logfile
  KNXD_OPTS="`grep KNXD_OPTS $configfile`"                                                                                                            2>&1 >>$logfile
  echo "Configure KNXd to use $KNXD_OPTS"                                                                                                             2>&1 >>$logfile
  sed -i  "s%KNXD_OPTS=.*%$KNXD_OPTS%g" $INPUTFILE                                                                                                    2>&1 >>$logfile
  ln -s REPLACEBYBASEFOLDER/webfrontend/cgi/plugins/REPLACEBYSUBFOLDER/bin/eibtime.pl REPLACEBYBASEFOLDER2/system/cron/cron.01min/REPLACEBYPLUGINNAME 2>&1 >>$logfile
  echo "Check, if KNXd Control Daemon is running"                                                                                                     2>&1 >>$logfile
  CS_PID=`ps -ef|grep "knxd/bin/server_control.pl"|grep -v grep |awk -F" " '{ print $2 }'`                                                            2>&1 >>$logfile
	if [ -z "$CS_PID" ]
	then
    echo "Process not found, no need to kill it"                                                                                                      2>&1 >>$logfile
  else
    echo "Process ID $CS_PID found, killing it"                                                                                                       2>&1 >>$logfile
    kill -15 $CS_PID                                                                                                                                  2>&1 >>$logfile
  fi
  echo "Try to start KNXd Control Daemon"                                                                                                             2>&1 >>$logfile
  REPLACEBYBASEFOLDER/webfrontend/cgi/plugins/REPLACEBYSUBFOLDER/bin/server_control.pl                                                                2>&1 >>$logfile &
  if [ $? -eq 0 ]
  then
    echo "KNXd Control Daemon restart successfully completed."                                                                                        2>&1 >>$logfile
  else
    echo "KNXd Control Daemon cannot be started. That's bad. Check the logfile!"                                                                      2>&1 >>$logfile
  fi
  echo "Try to read KNXd Version"                                                                                                                     2>&1 >>$logfile
  /usr/bin/knxd -V                                                                                                                                    2>&1 >>$logfile
  if [ $? -eq 0 ]
  then
    echo "KNXd Version successfully read"                                                                                                             2>&1 >>$logfile
    echo "Removing $flagfile"                                                                                                                         2>&1 >>$logfile
    rm $flagfile                                                                                                                                      2>&1 >>$logfile
    echo "Try to restart KNXd"                                                                                                                        2>&1 >>$logfile
    service knxd stop                                                                                                                                 2>&1 >>$logfile
    service knxd start                                                                                                                                2>&1 >>$logfile
    if [ $? -eq 0 ]
    then
      echo "KNXd successfully restarted."                                                                                                             2>&1 >>$logfile
      echo "Installation complete."                                                                                                                   2>&1 >>$logfile
      exit 0
    else
      echo "KNXd cannot be started. That's bad."                                                                                                      2>&1 >>$logfile
    fi
  else
    echo "KNXd Version cannot be read. That's bad."                                                                                                   2>&1 >>$logfile
  fi
else
  echo "Plugin modification already done."                                                                                                            2>&1 >>$logfile
  KNXD_OPTS="`grep KNXD_OPTS $configfile`"
  echo "Configure KNXd to use $KNXD_OPTS"                                                                                                             2>&1 >>$logfile
  sed -i  "s%KNXD_OPTS=.*%$KNXD_OPTS%g" $INPUTFILE
  echo "Check, if KNXd Control Daemon is running"                                                                                                     2>&1 >>$logfile
  CS_PID=`ps -ef|grep "knxd/bin/server_control.pl"|grep -v grep |awk -F" " '{ print $2 }'`                                                            2>&1 >>$logfile
	if [ -z "$CS_PID" ]
	then
    echo "Process not found, no need to kill it"                                                                                                      2>&1 >>$logfile
  else
    echo "Process ID $CS_PID found, killing it"                                                                                                       2>&1 >>$logfile
    kill -15 $CS_PID                                                                                                                                  2>&1 >>$logfile
  fi
  echo "Try to start KNXd Control Daemon"                                                                                                             2>&1 >>$logfile
  REPLACEBYBASEFOLDER/webfrontend/cgi/plugins/REPLACEBYSUBFOLDER/bin/server_control.pl                                                                2>&1 >>$logfile &
  if [ $? -eq 0 ]
  then
    echo "KNXd Control Daemon restart successfully completed."                                                                                        2>&1 >>$logfile
  else
    echo "KNXd Control Daemon cannot be started. That's bad. Check the logfile!"                                                                      2>&1 >>$logfile
  fi
  echo "Try to restart KNXd"                                                                                                                          2>&1 >>$logfile
  service knxd stop                                                                                                                                   2>&1 >>$logfile
  service knxd start                                                                                                                                  2>&1 >>$logfile
  if [ $? -eq 0 ]
  then
    echo "Restart successfully completed."                                                                                                            2>&1 >>$logfile
    exit 0
  else
    echo "KNXd cannot be started. That's bad."                                                                                                        2>&1 >>$logfile
  fi
fi

# When arriving here, something goes wrong
echo "Oh oh, I had problems. Please read the Plugin-Logfile for details."                                                                             2>&1 >>$logfile
exit 1
