#!/bin/bash
### BEGIN INIT INFO
# Provides:          KNXd
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: This file is for the KNXd Plugin.
# Description:       This file is for the KNXd Plugin.
### END INIT INFO

PATH="/sbin:/bin:/usr/sbin:/usr/bin:REPLACELBHOMEDIR/bin"
PATH=$PATH.":REPLACELBHOMEDIR/sbin"

. /lib/lsb/init-functions

### END INIT INFO

# Version v2018.3.11

logfile="REPLACELBPLOGDIR/knxd.log"
flagfile="REPLACELBPCONFIGDIR/modify.me"
configfile="REPLACELBPCONFIGDIR/knxd.cfg"
cronjob="REPLACELBHOMEDIR/system/cron/cron.01min/KNXd"
timescript="REPLACELBPHTMLAUTHDIR/bin/eibtime.pl"

INPUTFILE="/etc/knxd.conf"
echo "Uncommenting the KNXd section in rpimonitor if installed" >>$logfile 2>&1
find REPLACELBHOMEDIR/data/plugins/rpi_monitor*/ -name services.conf  -exec /bin/sed -i 's/^#KNXd#dynamic.5679/dynamic.5679/g' {} \; >>$logfile 2>&1
find REPLACELBHOMEDIR/data/plugins/rpi_monitor*/ -name services.conf  -exec /bin/sed -i 's/^#KNXd#dynamic.3672/dynamic.3672/g' {} \; >>$logfile 2>&1
find REPLACELBHOMEDIR/data/plugins/rpi_monitor*/ -name services.conf  -exec /bin/sed -i 's/^#KNXd#web.status.1.content.1.line.1="<b>KNXd/web.status.1.content.1.line.1="<b>KNXd/g' {} \; >>$logfile 2>&1
echo "Restart rpimonitor if installed"	 >>$logfile 2>&1
echo `sleep 30;systemctl restart rpimonitor 2>/dev/null` &

if [ -r $flagfile ]
then
  touch $logfile
  chown loxberry:loxberry $logfile
  chmod 666 $logfile
  echo "modify.me found. Installing KNXd Plugin."
  echo "modify.me found. Installing."                                                                                                                 2>&1 >>$logfile
  cd REPLACELBPDATADIR/                                                                                                                               2>&1 >>$logfile
  dpkg -i libpthsem*.deb                                                                                                                              2>&1 >>$logfile
  dpkg -i knxd_*.deb knxd-tools_*.deb                                                                                                                 2>&1 >>$logfile
  cd                                                                                                                                                  2>&1 >>$logfile
  KNXD_OPTS="`grep KNXD_OPTS $configfile`"                                                                                                            2>&1 >>$logfile
  echo "Configure KNXd to use $KNXD_OPTS"                                                                                                             2>&1 >>$logfile
  sed -i  "s%KNXD_OPTS=.*%$KNXD_OPTS%g" $INPUTFILE                                                                                                    2>&1 >>$logfile
  ln -s $timescript $cronjob                                                                                                                          2>&1 >>$logfile
  echo "Check, if KNXd Control Daemon is running"                                                                                                     2>&1 >>$logfile
  CS_PID=`ps -ef|grep "knxd/bin/server_control.pl"|grep -v grep |awk -F" " '{ print $2 }'`                                                            2>&1 >>$logfile
	if [ -z "$CS_PID" ]
	then
    echo "Process not found, try to start KNXd Control Daemon"                                                                                        2>&1 >>$logfile
	  REPLACELBPHTMLAUTHDIR/bin/server_control.pl                                                                                                     2>&1 >>$logfile &
	  if [ $? -eq 0 ]
	  then
	    echo "KNXd Control Daemon restart successfully completed."                                                                                      2>&1 >>$logfile
	  else
	    echo "KNXd Control Daemon cannot be started. That's bad. Check the logfile!"                                                                    2>&1 >>$logfile
	  fi
  else
    echo "Process ID $CS_PID found, no action"                                                                                                        2>&1 >>$logfile
  fi
  echo "Try to read KNXd Version"                                                                                                                     2>&1 >>$logfile
  /usr/bin/knxd -V                                                                                                                                    2>&1 >>$logfile
  if [ $? -eq 0 ]
  then
    echo "KNXd Version successfully read"                                                                                                             2>&1 >>$logfile
    echo "Removing $flagfile"                                                                                                                         2>&1 >>$logfile
    rm $flagfile                                                                                                                                      2>&1 >>$logfile
    echo "Try to restart KNXd"                                                                                                                        2>&1 >>$logfile
    service knxd stop                                                                                                                                 2>&1 >>$logfile
	  service knxd start                                                                                                                                  2>&1 >>$logfile
	  if [ $? -eq 0 ]
	  then
	    echo "Restart successfully completed."                                                                                                            2>&1 >>$logfile
	    echo "Create Time/Date cron job."                                                                                                                 2>&1 >>$logfile
			if [ -r "$cronjob" ]
			then
		    echo "Time/Date Cron job already exist."                                                                                                        2>&1 >>$logfile
			else
	  	  echo "Create Time/Date cron job."                                                                                                               2>&1 >>$logfile
			  ln -s $timescript $cronjob                                                                                                                      2>&1 >>$logfile
			  if [ $? -eq 0 ]
			  then
			    echo "Time/Date Cron job successfully created."                                                                                               2>&1 >>$logfile
			  else
			    echo "Time/Date Cron job creation failed."                                                                                                    2>&1 >>$logfile
			  fi
	    fi
      exit 0
    else
      echo "KNXd cannot be started. That's bad."                                                                                                      2>&1 >>$logfile
    fi
  else
    echo "KNXd Version cannot be read. That's bad."                                                                                                   2>&1 >>$logfile
  fi
else
  echo "Plugin modification already done."                                                                                                            2>&1 >>$logfile
  KNXD_OPTS="`grep KNXD_OPTS $configfile`"
  echo "Configure KNXd to use $KNXD_OPTS"                                                                                                             2>&1 >>$logfile
  sed -i  "s%KNXD_OPTS=.*%$KNXD_OPTS%g" $INPUTFILE
  echo "Check, if KNXd Control Daemon is running"                                                                                                     2>&1 >>$logfile
  CS_PID=`ps -ef|grep "knxd/bin/server_control.pl"|grep -v grep |awk -F" " '{ print $2 }'`                                                            2>&1 >>$logfile
	if [ -z "$CS_PID" ]
	then
    echo "Process not found, try to start KNXd Control Daemon"                                                                                        2>&1 >>$logfile
	  REPLACELBPHTMLAUTHDIR/bin/server_control.pl                                                              2>&1 >>$logfile &
	  if [ $? -eq 0 ]
	  then
	    echo "KNXd Control Daemon restart successfully completed."                                                                                      2>&1 >>$logfile
	  else
	    echo "KNXd Control Daemon cannot be started. That's bad. Check the logfile!"                                                                    2>&1 >>$logfile
	  fi
  else
    echo "Process ID $CS_PID found, no action"                                                                                                        2>&1 >>$logfile
  fi
  echo "Try to restart KNXd"                                                                                                                          2>&1 >>$logfile
  service knxd stop                                                                                                                                   2>&1 >>$logfile
  service knxd start                                                                                                                                  2>&1 >>$logfile
  if [ $? -eq 0 ]
  then
    echo "Restart successfully completed."                                                                                                            2>&1 >>$logfile
    echo "Create Time/Date cron job."                                                                                                                 2>&1 >>$logfile
		if [ -r "$cronjob" ]
		then
	    echo "Time/Date Cron job already exist."                                                                                                        2>&1 >>$logfile
		else
  	  echo "Create Time/Date cron job."                                                                                                               2>&1 >>$logfile
		  ln -s $timescript $cronjob                                                                                                                      2>&1 >>$logfile
		  if [ $? -eq 0 ]
		  then
		    echo "Time/Date Cron job successfully created."                                                                                               2>&1 >>$logfile
		  else
		    echo "Time/Date Cron job creation failed."                                                                                                    2>&1 >>$logfile
		  fi
    fi
    exit 0
  else
    echo "KNXd cannot be started. That's bad."                                                                                                        2>&1 >>$logfile
  fi
fi

# When arriving here, something goes wrong
echo "Oh oh, I had problems. Please read the Plugin-Logfile for details."                                                                             2>&1 >>$logfile
exit 0
